### ISSUE TITLE
As an operator, I can use the Service operator to manage the users within MySQL database

### ISSUE THREAD

**Issue by buhongw7583c** [Azure/azure-service-operator#1055]
This user story covers the following:
The Service Operator can add users with roles to MySQL databases. 

**Acceptance Criteria**
[Update this once the owner starts looking at the user story]

- [ ] The service operator can create a user within a MySQL database with role name, username and password. 

- [ ] The service operator can update the user's password

- [ ] The service operator can delete a user within the MySQL database. 

**Tasks**
Reference this issue when you create tasks for this user story
