### ISSUE TITLE
As an operator, I can use the service operator to manage a user within the PostgreSQL database

### ISSUE THREAD

**Issue by buhongw7583c** [Azure/azure-service-operator#1056]
**This user story covers the following**:
Be able to create/update/delete a user within the PostgreSQL database. 

**Acceptance Criteria**
[Update this once the owner starts looking at the user story]

- [ ] The service operator can create a user within a MySQL database with role name, username and password.
- [ ] The service operator can update the user's password
- [ ] The service operator can delete a user within the MySQL database.

**Tasks**
Reference this issue when you create tasks for this user story
