### ISSUE TITLE
As a user, I have documentation that helps me deploy the operator and use it

### ISSUE THREAD

**Issue by Azadehkhojandi** [Azure/azure-service-operator#11]
This user story covers the following:
Creation of README for deploying the operator, using it to deploy Azure services and running tests.

**Acceptance Criteria**
[Update this once the owner starts looking at the user story]

- [ ] Documentation covers instructions to deploy the operator based on the public docker image released.

- [ ] Documentation should cover instructions to setup their environment to build the code

- [ ] Documentation should cover how to deploy/delete//update Azure resources once the CRDs are installed (on Operator install) with example YAMLs and information on how to store the environment variables

- [ ] Documentation should cover how to run unit tests/integration tests

**Tasks**
Reference this issue when you create tasks for this user story
