### ISSUE TITLE
As a developer, I can create a service bus

### ISSUE THREAD

**Issue by timja** [Azure/azure-service-operator#1175]
Hi 👋 
We just saw that OSBA has been deprecated: https://github.com/Azure/open-service-broker-azure/commit/5cbcd7466727aee73c909776d731eeb342880391

In order to migrate we would need support for service buses

This user story covers the following:

Azure Service Bus
Queues
Topics
Namespaces

Creation of a resource helper library using Azure Go SDK that can be used to deploy/delete/update the resource. This can be used in the operator code.

**Acceptance Criteria**
[Update this once the owner starts looking at the user story]

- [ ] User can create an instance of the Azure Service Bus given the location and resource group using the helper library

- [ ] User can delete an particular instance of the Azure Service Bus using the helper library

- [ ] User can update the settings of a particular instance of the Azure Service Bus using the helper library

- [ ] Unit tests exist for the helper functions

- [ ] The service principal information, subscription ID and tenant ID can be passed as environment variables to the helper library

- [ ] The helper library has the ability to diagnose issues. (Discuss the logger we want to use)

**Epic reference***
#<issue number of epic that this user story accrues to>

**Tasks**
Reference this issue when you create tasks for this user story

**Comment by kyschouv** [comment]
Is there any ETA on this? I'm having to work around this manually right now, and I'd like to be able to use ASO for deploying and managing this.

**Comment by kyschouv** [comment]
We're probably going to have to drop ASO without this supported. Is there any update that can be shared here?

**Comment by babbageclunk** [comment]
Hi Kyle, support for Service Bus is definitely planned to be available at the same time as Event Grid - see the resource list here: https://github.com/Azure/azure-service-operator/issues/1192#issuecomment-722766539 
We're expecting to have an alpha available this quarter - once that's out the P1 resources should be close behind.

**Comment by theunrepentantgeek** [comment]
We've just released the [v2.0.0-alpha.0](https://github.com/Azure/azure-service-operator/releases/tag/v2.0.0-alpha.0) release of the operator, with support for Azure Service Bus.

Please have a go and let us know how you get on.

**Comment by kyschouv** [comment]
Awesome. When will it be installable via Operator Lifecycle Manager (operatorhub.io)? Also, are there any docs? Or just I just look at the CRDs after it's installed?
