### ISSUE TITLE
As a developer, I can use the CI/CD pipeline to validate that the EventHub Operator works correctly

### ISSUE THREAD

**Issue by Azadehkhojandi** [Azure/azure-service-operator#14]
This user story covers the following:
Creation of the CI/CD pipeline using Azure Devops for EventHub Operator. This pipeline will be used for other operators too after this.

**Acceptance Criteria**
[Update this once the owner starts looking at the user story]

- [ ] The CI pipeline runs for every pull request. It builds the code and runs unit tests

- [ ] All changes to the master branch trigger the CI/CD pipeline to build code, run unit tests in addition to also running integration tests and tagging releases in ACR and Github

- [ ] The pipeline to run integration tests can also be triggered manually when we need to test if things are working fine with the external Azure APIs

**Tasks**
Reference this issue when you create tasks for this user story
