### ISSUE TITLE
Outstanding items with resource status information

### ISSUE THREAD

**Issue by Porges** [Azure/azure-service-operator#1460]
- [x] Get rid of all `unable to produce type` errors and [make it fatal](https://github.com/Azure/k8s-infra/pull/205#discussion_r471845144). Fixed in Azure/k8s-infra#229.
- [x] Need to handle enum parameters in URLs. e.g. `Dnszones/{type}` expands to `DnszonesPTR`, `DnszonesSOA`, … Fixed by Azure/k8s-infra#230.
- [x] Investigate instances of “resource already defined differently” (13). Fixed by Azure/k8s-infra#231.
- [x] Add `controller-gen` status annotations.
- [x] Validate some example status types against real ARM (with test/demo controller).
- [x] #1838
- [x] Investigate missing status information (currently 289/1885 types). Some explained by items above. Azure/k8s-infra#231 reduces this to 199.
  - Note that this is addressed for all currently-used resource types; we currently error out if any types would be generated without status information.
- [ ] Get rid of all unable-to-extract-resource-name errors and [make it fatal](https://github.com/Azure/k8s-infra/pull/205#discussion_r471845030). (Some ideas here: we are matching things as resources that aren't really resources, we can be more strict on the checks by investigating the types to see if they are tagged as ARM resources or not.)

**Comment by matthchr** [comment]
- [x] Make missing (and exported) `Status` types fatal

**Comment by theunrepentantgeek** [comment]
Need at least some of these for our beta release, but some things can be deferred later.

**Comment by matthchr** [comment]
Need to confirm with @porges if we're done with all of this.

**Comment by matthchr** [comment]
unable-to-extract-resource-name shows up as error:

> E1004 12:00:17.216396   35744 swagger_type_extractor.go:84] 
Error extracting resource name (D:\go\src\github\azure-service-operator\v2\specs\azure-rest-api-specs\specification\resources\resource-mana
ger\Microsoft.Authorization\stable\2016-12-01\policyAssignments.json): 
unable to infer name from path "/{policyAssignmentId}": 
no group name (‘Microsoft…’ = "") found

**Comment by matthchr** [comment]
The last item in the checklist still needs to be fixed. Here's a list of some examples of where it's hit

```
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/solutions/resource-manager/Microsoft.Solutions/preview/2020-08-21-preview/managedapplications.json): unable to infer name from path "/{applicationId}": no group name (‘Microsoft…’) found in /{applicationId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Authorization/preview/2017-06-01-preview/policyAssignments.json): unable to infer name from path "/{policyAssignmentId}": no group name (‘Microsoft…’) found in /{policyAssignmentId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/authorization/resource-manager/Microsoft.Authorization/stable/2015-07-01/authorization-RoleAssignmentsCalls.json): unable to infer name from path "/{roleAssignmentId}": no group name (‘Microsoft…’) found in /{roleAssignmentId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/authorization/resource-manager/Microsoft.Authorization/preview/2020-08-01-preview/authorization-RoleAssignmentsCalls.json): unable to infer name from path "/{roleAssignmentId}": no group name (‘Microsoft…’) found in /{roleAssignmentId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/authorization/resource-manager/Microsoft.Authorization/preview/2017-10-01-preview/authorization-RoleAssignmentsCalls.json): unable to infer name from path "/{roleAssignmentId}": no group name (‘Microsoft…’) found in /{roleAssignmentId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/solutions/resource-manager/Microsoft.Solutions/stable/2019-07-01/managedapplications.json): unable to infer name from path "/{applicationId}": no group name (‘Microsoft…’) found in /{applicationId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2018-02-01/resources.json): unable to infer name from path "/{resourceId}": no group name (‘Microsoft…’) found in /{resourceId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2018-02-01/resources.json): unable to infer name from path "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}": no group name (‘Microsoft…’) found in /subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2016-09-01/resources.json): unable to infer name from path "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}": no group name (‘Microsoft…’) found in /subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2016-09-01/resources.json): unable to infer name from path "/{resourceId}": no group name (‘Microsoft…’) found in /{resourceId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2019-10-01/resources.json): unable to infer name from path "/{resourceId}": no group name (‘Microsoft…’) found in /{resourceId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2019-10-01/resources.json): unable to infer name from path "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}": no group name (‘Microsoft…’) found in /subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/trafficmanager/resource-manager/Microsoft.Network/stable/2018-03-01/trafficmanager.json): unable to infer name from path "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/trafficmanagerprofiles/{profileName}/{endpointType}/{endpointName}": multiple parameters in path
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2019-07-01/resources.json): unable to infer name from path "/{resourceId}": no group name (‘Microsoft…’) found in /{resourceId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2019-07-01/resources.json): unable to infer name from path "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}": no group name (‘Microsoft…’) found in /subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/solutions/resource-manager/Microsoft.Solutions/stable/2017-12-01/managedapplications.json): unable to infer name from path "/{applicationId}": no group name (‘Microsoft…’) found in /{applicationId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Authorization/stable/2020-09-01/policyAssignments.json): unable to infer name from path "/{policyAssignmentId}": no group name (‘Microsoft…’) found in /{policyAssignmentId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Authorization/stable/2019-06-01/policyAssignments.json): unable to infer name from path "/{policyAssignmentId}": no group name (‘Microsoft…’) found in /{policyAssignmentId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Authorization/stable/2019-01-01/policyAssignments.json): unable to infer name from path "/{policyAssignmentId}": no group name (‘Microsoft…’) found in /{policyAssignmentId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Solutions/stable/2017-09-01/managedapplications.json): unable to infer name from path "/{applicationId}": no group name (‘Microsoft…’) found in /{applicationId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Solutions/stable/2017-09-01/managedapplications.json): unable to infer name from path "/{applicationDefinitionId}": no group name (‘Microsoft…’) found in /{applicationDefinitionId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2019-03-01/resources.json): unable to infer name from path "/{resourceId}": no group name (‘Microsoft…’) found in /{resourceId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2019-03-01/resources.json): unable to infer name from path "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}": no group name (‘Microsoft…’) found in /subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/solutions/resource-manager/Microsoft.Solutions/preview/2018-09-01-preview/managedapplications.json): unable to infer name from path "/{applicationId}": no group name (‘Microsoft…’) found in /{applicationId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/solutions/resource-manager/Microsoft.Solutions/stable/2021-07-01/managedapplications.json): unable to infer name from path "/{applicationId}": no group name (‘Microsoft…’) found in /{applicationId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Authorization/stable/2016-12-01/policyAssignments.json): unable to infer name from path "/{policyAssignmentId}": no group name (‘Microsoft…’) found in /{policyAssignmentId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Solutions/stable/2018-06-01/managedapplications.json): unable to infer name from path "/{applicationId}": no group name (‘Microsoft…’) found in /{applicationId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Solutions/stable/2019-07-01/managedapplications.json): unable to infer name from path "/{applicationId}": no group name (‘Microsoft…’) found in /{applicationId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2019-05-10/resources.json): unable to infer name from path "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}": no group name (‘Microsoft…’) found in /subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2019-05-10/resources.json): unable to infer name from path "/{resourceId}": no group name (‘Microsoft…’) found in /{resourceId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2022-09-01/resources.json): unable to infer name from path "/{resourceId}": no group name (‘Microsoft…’) found in /{resourceId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2022-09-01/resources.json): unable to infer name from path "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}": no group name (‘Microsoft…’) found in /subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Authorization/stable/2018-05-01/policyAssignments.json): unable to infer name from path "/{policyAssignmentId}": no group name (‘Microsoft…’) found in /{policyAssignmentId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Authorization/stable/2021-06-01/policyAssignments.json): unable to infer name from path "/{policyAssignmentId}": no group name (‘Microsoft…’) found in /{policyAssignmentId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/trafficmanager/resource-manager/Microsoft.Network/stable/2017-05-01/trafficmanager.json): unable to infer name from path "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/trafficmanagerprofiles/{profileName}/{endpointType}/{endpointName}": multiple parameters in path
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Solutions/preview/2020-08-21-preview/managedapplications.json): unable to infer name from path "/{applicationId}": no group name (‘Microsoft…’) found in /{applicationId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2021-04-01/resources.json): unable to infer name from path "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}": no group name (‘Microsoft…’) found in /subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2021-04-01/resources.json): unable to infer name from path "/{resourceId}": no group name (‘Microsoft…’) found in /{resourceId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/authorization/resource-manager/Microsoft.Authorization/stable/2022-04-01/authorization-RoleAssignmentsCalls.json): unable to infer name from path "/{roleAssignmentId}": no group name (‘Microsoft…’) found in /{roleAssignmentId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2020-08-01/resources.json): unable to infer name from path "/{resourceId}": no group name (‘Microsoft…’) found in /{resourceId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2020-08-01/resources.json): unable to infer name from path "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}": no group name (‘Microsoft…’) found in /subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/authorization/resource-manager/Microsoft.Authorization/preview/2020-04-01-preview/authorization-RoleAssignmentsCalls.json): unable to infer name from path "/{roleId}": no group name (‘Microsoft…’) found in /{roleId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/authorization/resource-manager/Microsoft.Authorization/preview/2018-01-01-preview/authorization-RoleAssignmentsCalls.json): unable to infer name from path "/{roleId}": no group name (‘Microsoft…’) found in /{roleId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Authorization/stable/2020-03-01/policyAssignments.json): unable to infer name from path "/{policyAssignmentId}": no group name (‘Microsoft…’) found in /{policyAssignmentId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2020-06-01/resources.json): unable to infer name from path "/{resourceId}": no group name (‘Microsoft…’) found in /{resourceId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2020-06-01/resources.json): unable to infer name from path "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}": no group name (‘Microsoft…’) found in /subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/solutions/resource-manager/Microsoft.Solutions/stable/2017-09-01/managedapplications.json): unable to infer name from path "/{applicationId}": no group name (‘Microsoft…’) found in /{applicationId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2016-09-01/links.json): unable to infer name from path "/{linkId}": no group name (‘Microsoft…’) found in /{linkId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2016-02-01/resources.json): unable to infer name from path "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}": no group name (‘Microsoft…’) found in /subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2019-08-01/resources.json): unable to infer name from path "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}": no group name (‘Microsoft…’) found in /subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2019-08-01/resources.json): unable to infer name from path "/{resourceId}": no group name (‘Microsoft…’) found in /{resourceId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/solutions/resource-manager/Microsoft.Solutions/stable/2018-02-01/managedapplications.json): unable to infer name from path "/{applicationId}": no group name (‘Microsoft…’) found in /{applicationId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2017-05-10/resources.json): unable to infer name from path "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}": no group name (‘Microsoft…’) found in /subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2017-05-10/resources.json): unable to infer name from path "/{resourceId}": no group name (‘Microsoft…’) found in /{resourceId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Authorization/stable/2022-06-01/policyAssignments.json): unable to infer name from path "/{policyAssignmentId}": no group name (‘Microsoft…’) found in /{policyAssignmentId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2020-10-01/resources.json): unable to infer name from path "/{resourceId}": no group name (‘Microsoft…’) found in /{resourceId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2020-10-01/resources.json): unable to infer name from path "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}": no group name (‘Microsoft…’) found in /subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/solutions/resource-manager/Microsoft.Solutions/preview/2021-02-01-preview/managedapplications.json): unable to infer name from path "/{applicationId}": no group name (‘Microsoft…’) found in /{applicationId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2015-11-01/resources.json): unable to infer name from path "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}": no group name (‘Microsoft…’) found in /subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Solutions/preview/2016-09-01-preview/managedapplications.json): unable to infer name from path "/{applianceId}": no group name (‘Microsoft…’) found in /{applianceId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Solutions/preview/2016-09-01-preview/managedapplications.json): unable to infer name from path "/{applianceDefinitionId}": no group name (‘Microsoft…’) found in /{applianceDefinitionId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/solutions/resource-manager/Microsoft.Solutions/stable/2018-06-01/managedapplications.json): unable to infer name from path "/{applicationId}": no group name (‘Microsoft…’) found in /{applicationId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2018-05-01/resources.json): unable to infer name from path "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}": no group name (‘Microsoft…’) found in /subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2018-05-01/resources.json): unable to infer name from path "/{resourceId}": no group name (‘Microsoft…’) found in /{resourceId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/trafficmanager/resource-manager/Microsoft.Network/stable/2018-02-01/trafficmanager.json): unable to infer name from path "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/trafficmanagerprofiles/{profileName}/{endpointType}/{endpointName}": multiple parameters in path
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/authorization/resource-manager/Microsoft.Authorization/preview/2018-09-01-preview/authorization-RoleAssignmentsCalls.json): unable to infer name from path "/{roleId}": no group name (‘Microsoft…’) found in /{roleId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Authorization/preview/2015-10-01-preview/policy.json): unable to infer name from path "/{policyAssignmentId}": no group name (‘Microsoft…’) found in /{policyAssignmentId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/authorization/resource-manager/Microsoft.Authorization/preview/2020-03-01-preview/authorization-RoleAssignmentsCalls.json): unable to infer name from path "/{roleAssignmentId}": no group name (‘Microsoft…’) found in /{roleAssignmentId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2019-05-01/resources.json): unable to infer name from path "/{resourceId}": no group name (‘Microsoft…’) found in /{resourceId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2019-05-01/resources.json): unable to infer name from path "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}": no group name (‘Microsoft…’) found in /subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/trafficmanager/resource-manager/Microsoft.Network/stable/2018-04-01/trafficmanager.json): unable to infer name from path "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/trafficmanagerprofiles/{profileName}/{endpointType}/{endpointName}": multiple parameters in path
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/authorization/resource-manager/Microsoft.Authorization/preview/2020-10-01-preview/authorization-RoleAssignmentsCalls.json): unable to infer name from path "/{roleAssignmentId}": no group name (‘Microsoft…’) found in /{roleAssignmentId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Authorization/stable/2016-04-01/policy.json): unable to infer name from path "/{policyAssignmentId}": no group name (‘Microsoft…’) found in /{policyAssignmentId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/solutions/resource-manager/Microsoft.Solutions/stable/2018-03-01/managedapplications.json): unable to infer name from path "/{applicationId}": no group name (‘Microsoft…’) found in /{applicationId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Authorization/stable/2018-03-01/policyAssignments.json): unable to infer name from path "/{policyAssignmentId}": no group name (‘Microsoft…’) found in /{policyAssignmentId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2021-01-01/resources.json): unable to infer name from path "/{resourceId}": no group name (‘Microsoft…’) found in /{resourceId}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2021-01-01/resources.json): unable to infer name from path "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}": no group name (‘Microsoft…’) found in /subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Resources/stable/2016-07-01/resources.json): unable to infer name from path "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}": no group name (‘Microsoft…’) found in /subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}
Error extracting resource name (/home/matthchr/work/github/azure-service-operator/v2/specs/azure-rest-api-specs/specification/resources/resource-manager/Microsoft.Authorization/stable/2019-09-01/policyAssignments.json): unable to infer name from path "/{policyAssignmentId}": no group name (‘Microsoft…’) found in /{policyAssignmentId}
```

**Comment by matthchr** [comment]
We still need to do this but it's not super high priority

**Comment by theunrepentantgeek** [comment]
Remaining task extracted.
