### ISSUE TITLE
As a developer, I can write controller tests that don't interact with Azure

### ISSUE THREAD

**Issue by szoio** [Azure/azure-service-operator#227]
This user story covers the following:

Instead of controller unit tests interacting with Azure (via the resource managers), they interact with a mocked version of the resource manager that doesn't interact with Azure directly.

**Acceptance Criteria**
[Update this once the owner starts looking at the user story]

- [ ] User can create an instance of the <Azure service name> given the location and resource group using the helper library

- [ ] User can delete an particular instance of the <Azure service name> using the helper library

- [ ] User can update the settings of a particular instance of the <Azure service name> using the helper library

- [ ] Unit tests exist for the helper functions

- [ ] The service principal information, subscription ID and tenant ID can be passed as environment variables to the helper library

- [ ] The helper library has the ability to diagnose issues. (Discuss the logger we want to use)

**Epic reference***
#<issue number of epic that this user story accrues to>

**Tasks**
Reference this issue when you create tasks for this user story
