### ISSUE TITLE
As a user, I can deploy Azure API Management service using Azure Go SDK

### ISSUE THREAD

**Issue by jananivMS** [Azure/azure-service-operator#24]
This user story covers the following:
Creation of  a resource helper library using Azure Go SDK that can be used to deploy/delete/update the resource. This can be used in the operator code.

**Acceptance Criteria**
[Update this once the owner starts looking at the user story]

- [ ] User can create an instance of the Azure API management service given the location and resource group using the helper library

- [ ] User can delete an particular instance of the Azure API management service using the helper library

- [ ] User can update the settings of a particular instance of the API management service using the helper library

- [ ] Unit tests exist for the helper functions

- [ ] The service principal information, subscription ID and tenant ID can be passed as environment variables to the helper library

- [ ] The helper library has the ability to diagnose issues. (Discuss the logger we want to use)

**Tasks**
Add a link to tasks you would like to create for this user story
