### ISSUE TITLE
As a user, I can deploy a Kubernetes operator to install Azure API management service using a Custom Resource Definition

### ISSUE THREAD

**Issue by jananivMS** [Azure/azure-service-operator#26]
This user story covers the following:
Creation of the Kubernetes service operator scaffolding using Kubebuilder. The operator would utilize the helper library developed  using Go SDK to perform the actual resource deployment.

**Acceptance Criteria**
[Update this once the owner starts looking at the user story]

- [ ] User can install a Custom Resource Definition (CRD) for Azure API management service on the Kubernetes cluster

- [ ] User can install a API management service instance using the CRD in an YAML file

- [ ] User can update the settings of a particular instance of the API management service using the CRD

- [ ] User can delete the instance of the API management service using the CRD

- [ ] User gets clear information on why an operation failed and how to remedy it

**Tasks**
Reference this issue when you create tasks for this user story
