### ISSUE TITLE
As a user, I can use the Azure Go SDK to create a Azure Data Lake storage

### ISSUE THREAD

**Issue by jananivMS** [Azure/azure-service-operator#329]
This user story covers the following:
Creation of a resource helper library using Azure Go SDK that can be used to deploy/delete/update the resource. This can be used in the operator code.

**Acceptance Criteria**
[Update this once the owner starts looking at the user story]

- [ ] User can create a storage account enabled for Azure Data Lake given the spec

- [ ] User can delete a storage account

- [ ] User can create a Data Lake File System given a storage account

- [ ] User can delete a Data Lake File System

- [ ] Tests exist for the helper functions

- [ ] The service principal information, subscription ID and tenant ID can be passed as environment variables to the helper library

- [ ] The helper library has logging to diagnose issues

**Epic reference***
#316 

**Tasks**
Reference this issue when you create tasks for this user story
