### ISSUE TITLE
As a user, I can deploy Azure EventHub using Azure Go SDK

### ISSUE THREAD

**Issue by jananivMS** [Azure/azure-service-operator#60]
This user story covers the following:
Creation of a resource helper library using Azure Go SDK that can be used to deploy/delete/update eventhub and eventhub namespace. This can be used in the operator code.

**Acceptance Criteria**

- [ ] User can create an instance of the Azure EventHub given the location and resource group using the helper library

- [ ] User can delete an particular instance of the Azure EventHub using the helper library

- [ ] User can update the settings of a particular instance of the Azure EventHub using the helper library

- [ ] Unit tests exist for the helper functions

- [ ] The service principal information, subscription ID and tenant ID can be passed as environment variables to the helper library

- [ ] The helper library has the ability to diagnose issues. 

**Tasks**
Reference this issue when you create tasks for this user story
