### ISSUE TITLE
[Microsoft Open Source Checklist] Include required files in the root directory of repo

### ISSUE THREAD

**Issue by jananivMS** [Azure/azure-service-operator#609]
**Done criteria **
This is the "done" criteria for this task

- [x] A README.md file describing the purpose and state of the repository, with a link to the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct) and a description of any third-party code included in the repository. A good README file is often critical to project success.
- [x] A LICENSE.txt file with the [MIT license text](https://docs.opensource.microsoft.com/content/releasing/license.html). Include your project name above the copyright statement. Licenses other than MIT must be cleared with CELA.
- [x] A CONTRIBUTING.md file with instructions on contributing to the project that must include at least the [minimum required information](https://docs.opensource.microsoft.com/content/releasing/accepting-contributions.html). That minimum information includes that contributions to Microsoft projects are subject to our Contributor License Agreement.

- Additionally, consider providing technical guidance like build instructions, coding conventions, or a project roadmap in the CONTRIBUTING.md file.

- [ ] Telemetry Notice. If the release has code that enables Microsoft to collect telemetry, also include in the repository:
instructions to turn off the telemetry;
this [data collection notice](https://docs.opensource.microsoft.com/content/releasing/telemetry.html) in a the README.md file.
- [x] Security Reporting Instructions. Include instructions that enable users to privately report security vulnerabilities found in your project. Sample instructions are [here](https://docs.opensource.microsoft.com/content/releasing/security.html).
