### ISSUE TITLE
As a user, I can deploy a Kubernetes operator to install Azure EventHub using a Custom Resource Definition

### ISSUE THREAD

**Issue by jananivMS** [Azure/azure-service-operator#61]
This user story covers the following:
Creation of a resource helper library using Azure Go SDK that can be used to deploy/delete/update the resource. This can be used in the operator code.

**Acceptance Criteria**
- [ ] User can install a Custom Resource Definition (CRD) for Azure EventHub and EventHub namespace on the Kubernetes cluster

- [ ] User can install Azure EventHub and EventHub namespace instance using the CRD in an YAML file

- [ ] User can update the settings of a particular instance of the Azure EventHub and EventHub namespace using the CRD

- [ ] User can delete the instance of the Azure EventHub and EventHub namespace using the CRD

- [ ] User gets clear information on why an operation failed and how to remedy it

**Tasks**
Reference this issue when you create tasks for this user story
