### ISSUE TITLE
[Microsoft Open Source Checklist] Remove sensitive assets and review content

### ISSUE THREAD

**Issue by jananivMS** [Azure/azure-service-operator#610]
**Done criteria **
This is the "done" criteria for this task

- [x] Remove any reference in the code to internal or confidential information, including internal paths, tools, codenames, proprietary fonts, internal telemetry and email aliases.
- [ ] Remove any trademarks or product icons.
- [x] Prepare the code and commit history [for publication](https://docs.opensource.microsoft.com/content/releasing/going-public.html), including running [PoliCheck](http://aka.ms/policheckinfo).
