### ISSUE TITLE
Task: CosmosDB: Investigate what these requirements entail and create actionable tassk

### ISSUE THREAD

**Issue by jananivMS** [Azure/azure-service-operator#881]
The customer would like to configure these when creating the CosmosDB. 

1. Need ability to configure these for cosmos dB (all of these are what you see when you create a cosmosDB instance from the portal)
- [X] Account Location
- [X] Resource Group
- [X] Name
- [X] Tags (from labels)
- [ ] MongoDB version #915 
- [ ] Virtual Network Rules #918 
- [ ] Firewall Rules #917 
- [ ] Geo-Redundancy #919 
- [ ] Multi-Region Writes #921 
- [ ] Notebooks Preview #922 
- [ ] Additional API Types: Table, Cassandra, Gremlin #923 
- [ ] Account Type: Production, Non-Production ???

This task is to analyze the above along with the cosmosDB SDK in hand, and come up with more actionable and clear tasks for each of these.

**Done criteria**
This is the "done" criteria for this task

- [ ] Actionable tasks exist for satisfying the above requirements from the customer
