### ISSUE TITLE
As a user, I can deploy Azure SQL server using Azure Go SDK

### ISSUE THREAD

**Issue by jananivMS** [Azure/azure-service-operator#97]
This user story covers the following:
Creation of a resource helper library using Azure Go SDK that can be used to deploy/delete/update the resource. This can be used in the operator code.

**Acceptance Criteria**
[Update this once the owner starts looking at the user story]

- [ ] User can create an instance of Azure SQL given the location and resource group using the helper library

- [ ] User can delete an particular instance of Azure SQL using the helper library

- [ ] User can update the settings of a particular instance of Azure SQL using the helper library

- [ ] Unit tests exist for the helper functions

- [ ] The service principal information, subscription ID and tenant ID can be passed as environment variables to the helper library

- [ ] The helper library has the ability to diagnose issues

**Epic reference***
#7 

**Tasks**
Reference this issue when you create tasks for this user story
