### ISSUE TITLE
As a user, I can deploy a Kubernetes operator to install Azure SQL server using a Custom Resource Definition

### ISSUE THREAD

**Issue by jananivMS** [Azure/azure-service-operator#98]
This user story covers the following:
Creation of the Kubernetes service operator scaffolding using Kubebuilder. The operator would utilize the helper library developed using Go SDK to perform the actual resource deployment.

**Acceptance Criteria**
[Update this once the owner starts looking at the user story]

- [x] User can install a Custom Resource Definition (CRD) for Azure SQL service on the Kubernetes cluster

- [x] User can install/update/delete a Azure SQL server instance using the CRD in an YAML file
- [ ] User can install/update/delete a Azure SQL DB using the CRD in an YAML file
- [ ] User can install/update/delete a Azure SQL firewall rule using the CRD in an YAML file
- [ ] User gets clear information on why an operation failed and how to remedy it
- [ ] User can roll credentials on sql server
- [ ] Instrument sql server with prometheus metrics

**Epic reference***
#7 

**Tasks**
Reference this issue when you create tasks for this user story
